name: "📝 Docs"
description: "버그 수정"
labels: ["Type: Docs :docs:"]
body:
  - type: textarea
    attributes:
      label: ❓ 설명
      description: 어떤 문서를 작업했는지 설명해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
